#
# This is free software.
# 

name: Emuelec-CI

on:
  push:
    tags:
        -.*
    # branches: 
        # - master
  # schedule:
    # - cron: 0 20 * * *
  # release:
    # types: [published]

jobs:

  build_emuelec:

    name: Build EmuELEC
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Prepare
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
            sudo apt update && sudo apt upgrade
            sudo apt-get install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang
            
      - name: Compile firmware
        run: |
          PROJECT=Amlogic ARCH=arm DISTRO=EmuELEC make image

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: EmuELEC
          path: ./repo
