#
# This is free software.
# 

name: EmuELEC-CI

on:
  watch:
    types: started
  push:
    tags:
        -.*
    # branches: 
        # - master
  # schedule:
    # - cron: 0 20 * * *
  # release:
    # types: [published]
      
env:
  SSH_ACTIONS: false

jobs:

  build_emuelec:

    name: Build EmuELEC
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      
      - name: Prepare
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
            df -h
            docker rmi `docker images -q`
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
            sudo -E apt-get update
            #sudo rm -rf /usr/share/dotnet /var/lib/mysql /etc/php /etc/apt/sources.list.d /usr/local/go
            #sudo -E apt-get -y remove ansible* aws* swift* podman* docker* skopeo* dotnet* erlang* firefox* google* gecko* chrome* cabal* ghc* haskell* hhvm* azul* adopt* ant* gradle* maven* kind* kubectl* mono* mysql* php* psql* mongodb* swig* android* golang*
            sudo -E apt-get -y autoremove --purge            
            #sudo -E apt update && sudo apt upgrade
            sudo -E apt-get -y install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4   bc patchutils gperf lzop xfonts-utils xsltproc libjson-perl default-jre
            #bc lsdiff gperf lzop mkfontscale mkfontdir bdftopcf xsltproc perl
            #sudo -E apt-get -y autoremove --purge
            sudo -E apt-get clean
            df -h
            
      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@main
        if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
           
      - name: Compile firmware
        run: |
          #PROJECT=Amlogic-ng ARCH=arm DISTRO=EmuELEC make -j8 image
          #cd EmuELEC
          ./emuelec-addon.sh

      - name: Check space usage
        if: (!cancelled())
        run: df -hT

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: EmuELEC
          path: ./repo
